Feature/pn 2517
pagopa/pn-logextractor-be pull request #4
Opened 2022-11-07 17:26 UTC by fdammassa

Build and deploy automation

2022-11-09 11:26 UTC, marco-vit-pagopa requested changes
Qualche cambiamento, soprattutto su gestione password

2022-11-09 11:26 UTC, marco-vit-pagopa commented on scripts/aws/deployBackend.sh
> +echo "OPENSEARCH_PASSWORD="${OPENSEARCH_PASSWORD}
Eviterei di loggare la password

2022-11-09 11:26 UTC, marco-vit-pagopa commented on scripts/aws/deployBackend.sh
> +        "ContainerEnvEntry19=ALLOWED_ORIGIN=${AllowedOrigin}" \
Questo non l'ho capito. Perché viene passato come parametro tutta la riga e non solo le variabili ?

2022-11-09 11:26 UTC, marco-vit-pagopa commented on scripts/aws/deployInfra.sh
> +  "OpenSearchMasterPaassword=${OPENSEARCH_MASTER_PASSWORD}"
La password rimane visibile in chiaro tra i parametri del template

2022-11-09 11:26 UTC, marco-vit-pagopa commented on scripts/aws/fragments/services.yaml
>                AWS: "*"
Mi sembra un po' troppo permissivo

2022-11-09 11:26 UTC, marco-vit-pagopa commented on scripts/aws/main.yaml
> +
Passarla come parametro di tipo String la espone in chiaro. Preferirei usare una [dynamic reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html)

2022-11-09 11:38 UTC, fdammassa commented on scripts/aws/deployBackend.sh
> +        "ContainerEnvEntry19=ALLOWED_ORIGIN=${AllowedOrigin}" \
@marco-vit-pagopa questi sono gli input dello stack nested ecs-service.yaml che ha sempre ricevuto i parametri come "chiave=valore"; pensi ci sia un altro modo per inizializzarlo?

2022-11-09 17:54 UTC, fdammassa commented on scripts/aws/fragments/services.yaml
>                AWS: "*"
@marco-vit-pagopa lasciata la policy così, da approfondire se possibile una restriction per IP o security group

2022-11-09 19:30 UTC, marco-vit-pagopa approved these changes

2022-11-14 09:18 UTC, marco-vit-pagopa approved these changes
Ok.

2022-11-14 09:27 UTC, merged