Feature/pn-4493
pagopa/pn-logextractor-be pull request #43
Opened 2023-03-13 15:51 UTC by acolella92

2023-03-13 16:23 UTC, MTurraPpa requested changes

2023-03-13 16:23 UTC, MTurraPpa commented on src/main/java/it/gov/pagopa/logextractor/service/LogServiceImpl.java
> +	@Value("${external.safeStorage.downloadFile.downloadUrl}")
Non credo che c'entra il download da safestorage? a cosa di riferisce questo campo?

2023-03-13 17:20 UTC, acolella92 commented on src/main/java/it/gov/pagopa/logextractor/service/LogServiceImpl.java
> +	@Value("${external.safeStorage.downloadFile.downloadUrl}")
si tratta di un refuso, correzione apportata e committata

2023-03-15 08:39 UTC, MTurraPpa requested changes

2023-03-15 08:39 UTC, MTurraPpa commented on src/main/resources/application-dev.properties
> +external.s3.downloadFile.downloadUrl=http://localhost:3001
Possiamo dare un nome meno generico? perché adesso a te è chiaro che si tratta del url al bucket S3 che contiene le SAML request di SPID/CIE. Ma un domani se qualcuno va a vedere il codice fa fatica a risalire a questa informazione.

2023-03-15 13:26 UTC, acolella92 commented on src/main/resources/application-dev.properties
> +external.s3.downloadFile.downloadUrl=http://localhost:3001
Modifica al nome apportata

2023-03-15 13:40 UTC, MTurraPpa requested changes
Potete verificare la copertura del codice?

2023-03-22 09:07 UTC, MTurraPpa approved these changes

2023-03-30 13:45 UTC, merged